Vagrant.configure("2") do |config|
  # Define the Ansible controller machine
  config.vm.define "ansible2-controller" do |ansible|
    ansible.vm.box = "ubuntu/jammy64"
    ansible.vm.hostname = "ansible-controller"
    ansible.vm.network "public_network", ip: "192.168.0.213", bridge: "eno3"
    ansible.vm.network "forwarded_port", guest: 8070, host: 8074 # Forwarding port 8070 to a different host port

    ansible.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 4
    end

    # Provisioning to update, upgrade, install Ansible, set password, and create files
    ansible.vm.provision "shell", inline: <<-SHELL
      # Update and upgrade the system
      sudo apt-get update -y
      sudo apt-get upgrade -y

      # Set the password for the vagrant user
      echo "vagrant:comfac123" | sudo chpasswd

      # Install Ansible
      sudo apt-get install -y software-properties-common
      sudo add-apt-repository --yes --update ppa:ansible/ansible
      sudo apt-get install -y ansible

    SHELL
  end
end
